ALTER TABLE TB_MTT_CIDADE 
    ADD CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (tb_mtt_estado_id) REFERENCES TB_MTT_ESTADO (id);

ALTER TABLE TB_MTT_VEICULO 
    ADD CONSTRAINT FK_VEICULO_USUARIO FOREIGN KEY (tb_mtt_usuario_id) REFERENCES TB_MTT_USUARIO (id);

ALTER TABLE TB_MTT_CAMERA 
    ADD CONSTRAINT FK_CAMERA_FILIAL FOREIGN KEY (tb_mtt_filial_id) REFERENCES TB_MTT_FILIAL (id);

ALTER TABLE TB_MTT_IOT 
    ADD CONSTRAINT FK_IOT_VEICULO FOREIGN KEY (tb_mtt_veiculo_id) REFERENCES TB_MTT_VEICULO (id);

ALTER TABLE TB_MTT_LOGRADOURO 
    ADD CONSTRAINT FK_LOGRADOURO_USUARIO FOREIGN KEY (tb_mtt_usuario_id) REFERENCES TB_MTT_USUARIO (id);

ALTER TABLE TB_MTT_LOGRADOURO 
    ADD CONSTRAINT FK_LOGRADOURO_FILIAL FOREIGN KEY (tb_mtt_filial_id) REFERENCES TB_MTT_FILIAL (id);

ALTER TABLE TB_MTT_LOGRADOURO 
    ADD CONSTRAINT FK_LOGRADOURO_CIDADE FOREIGN KEY (tb_mtt_cidade_id) REFERENCES TB_MTT_CIDADE (id);
