CREATE UNIQUE INDEX IDX_LOGRADOURO_USUARIO_UNQ ON TB_MTT_LOGRADOURO (tb_mtt_usuario_id) WHERE tb_mtt_usuario_id IS NOT NULL;
CREATE UNIQUE INDEX IDX_LOGRADOURO_FILIAL_UNQ ON TB_MTT_LOGRADOURO (tb_mtt_filial_id) WHERE tb_mtt_filial_id IS NOT NULL;
